### ISSUE TITLE
Question with regards to the data source

### ISSUE THREAD

**Issue by sharun-s** [cfalcondair/wikivoyage_search#2]
This is a cool repo! I am trying to do something similar but with the actual index dumps wikimedia generates [https://dumps.wikimedia.org/other/cirrussearch/current/] and got stuck setting up the right coordinate->geo point mappings. Was wondering why you chose to download the article dumps instead of the index dumps/perform xml parsing etc...performance/storage reasons or something else? 
Did you try bulk importing the index dumps? Seems to work for me but  haven't figured out how to convert the coordinate fields into geopoints.

**Comment by sharun-s** [comment]
Apparently the coordinates type can't be converted to geo_point after the mappings are auto generated during the bulk import. Had to save the mappings to disk, modify coordinate type in that file. Then delete the index. Recreate a new index with the local mappings file. And re-import the data. Strange non-intuitive process. Anyways resolved my problem so closing this issue.

**Comment by cfdair** [comment]
Geez that sounds like a hassle. This was a take-home test and they specified that they wanted me to parse the articles themselves.

First issue resolved and I didn't even have to do anything. ;)

**Comment by sharun-s** [comment]
ah I see. Still this repo was useful to me as a reference. So thanks for putting it up!
